import type { Room } from '@/entities/room'

export const MOCK_ROOM: Room = {
  id: 'mock-107',
  slug: 'ofis-107',
  title: 'Офис №107',
  roomNumber: '107',
  type: 'Офис',
  area: 262.6,
  floor: 1,
  layoutType: 'Открытая',
  water: true,
  wc: true,
  windows: true,
  entrance: 'Отдельный',
  rentType: 'Долгосрочная',
  internet: 'Оптоволокно',
  minRentTerm: 'от 6 месяцев',
  priceMonth: 262600,
  priceM2: 1000,
  description:
    '<p>Просторный офис открытой планировки на первом этаже с отдельным входом. Площадь 262,6&nbsp;м² позволяет разместить большую команду или зонировать пространство под собственные нужды.</p><ul><li>Отдельный вход с улицы — независимый доступ круглосуточно</li><li>Собственная система водоснабжения и санузел</li><li>Кондиционирование воздуха</li><li>Полы — керамическая плитка</li><li>Оптоволоконный интернет до 1 Гбит/с</li></ul>',
  suitableFor: ['Любые организации'],
  status: 'FREE',
  showOnHome: true,
  photos: [
    { id: 'p7', url: '/images/оф107-7.jpg', order: 0 },
    { id: 'p1', url: '/images/оф107-1.jpg', order: 1 },
    { id: 'p2', url: '/images/оф107-2.jpg', order: 2 },
    { id: 'p3', url: '/images/оф107-3.jpg', order: 3 },
    { id: 'p4', url: '/images/оф107-4.jpg', order: 4 },
    { id: 'p5', url: '/images/оф107-5.jpg', order: 5 },
    { id: 'p6', url: '/images/оф107-6.jpg', order: 6 },
    { id: 'p8', url: '/images/оф107-8.jpg', order: 7 },
  ],
}

export const MOCK_BUILDING_ORGS = [
  {
    id: 'org-1',
    name: 'ТКБ Банк',
    category: 'bank',
    description:
      'ТКБ Банк — российский банк с более чем 30-летней историей, входящий в топ-10 частных банков по активам. Широкий спектр услуг для частных лиц и бизнеса.',
    website: 'https://www.tkbbank.ru',
    floor: 2,
    color: 'blue',
    order: 0,
    active: true,
  },
  {
    id: 'org-2',
    name: 'СберПраво',
    category: 'service',
    description:
      'Юридический сервис экосистемы Сбера: консультации, подготовка документов, судебное представительство. Банкротство физлиц, семейные и жилищные споры.',
    website: 'https://sberpravo.ru',
    floor: 3,
    color: 'green',
    order: 1,
    active: true,
  },
  {
    id: 'org-3',
    name: 'I Dolci',
    category: 'food',
    description:
      'Сеть кафе-кондитерских с натуральными десертами ручной работы: бисквитные и муссовые торты, пирожные, чизкейки. Доставка, мастер-классы, кейтеринг.',
    website: 'https://idolci.ru',
    floor: 1,
    color: 'amber',
    order: 2,
    active: true,
  },
  {
    id: 'org-4',
    name: 'Русский Фейерверк',
    category: 'retail',
    description:
      'Сеть магазинов пиротехники, представленная в десятках городов России. Безопасная продукция, система скидок до 40% по карте лояльности.',
    website: 'https://rusfireworks.ru',
    floor: 1,
    color: 'red',
    order: 3,
    active: true,
  },
  {
    id: 'org-5',
    name: 'Angiopharm',
    category: 'other',
    description:
      'Лаборатория-производитель профессиональной уходовой косметики. Собственная разработка — рекомбинантный ангиогенин. Производство в наукограде Кольцово.',
    website: 'https://angiopharm.com',
    floor: 4,
    color: 'purple',
    order: 4,
    active: true,
  },
  {
    id: 'org-6',
    name: 'НРК-Р.О.С.Т.',
    category: 'service',
    description:
      'Лидер регистраторской отрасли России. Ведение реестров акционеров, специализированный депозитарий, корпоративный консалтинг, цифровые сервисы для эмитентов.',
    website: 'https://rrost.ru',
    floor: 5,
    color: 'indigo',
    order: 5,
    active: true,
  },
  {
    id: 'org-7',
    name: 'ИНПЭС',
    category: 'other',
    description:
      'Проектная компания, специализирующаяся на комплексном проектировании объектов электросетевой инфраструктуры. Опыт в 40 регионах России.',
    website: 'https://inpes.ru',
    floor: 6,
    color: 'teal',
    order: 6,
    active: true,
  },
  {
    id: 'org-8',
    name: 'Имплант Сибири',
    category: 'other',
    description:
      'Стоматологическая клиника с более чем 20-летним опытом. Имплантация, протезирование, пародонтология. Безболезненное лечение с использованием передовых технологий.',
    website: 'https://implantsibir.ru',
    floor: 2,
    color: 'orange',
    order: 7,
    active: true,
  },
]
