import type { Room } from '@/entities/room'

export const MOCK_ROOM: Room = {
  id: 'mock-107',
  slug: 'ofis-107',
  title: 'Офис №107',
  roomNumber: '107',
  type: 'Офис',
  area: 262.6,
  floor: 1,
  layoutType: 'Открытая',
  water: true,
  wc: true,
  windows: true,
  entrance: 'Отдельный',
  rentType: 'Долгосрочная',
  internet: 'Оптоволокно',
  minRentTerm: 'от 6 месяцев',
  priceMonth: 262600,
  priceM2: 1000,
  description:
    '<p>Просторный офис открытой планировки на первом этаже с отдельным входом. Площадь 262,6&nbsp;м² позволяет разместить большую команду или зонировать пространство под собственные нужды.</p><ul><li>Отдельный вход с улицы — независимый доступ круглосуточно</li><li>Собственная система водоснабжения и санузел</li><li>Кондиционирование воздуха</li><li>Полы — керамическая плитка</li><li>Оптоволоконный интернет до 1 Гбит/с</li></ul>',
  suitableFor: ['Любые организации'],
  status: 'FREE',
  showOnHome: true,
  photos: [
    { id: 'p7', url: '/images/оф107-7.jpg', order: 0 },
    { id: 'p1', url: '/images/оф107-1.jpg', order: 1 },
    { id: 'p2', url: '/images/оф107-2.jpg', order: 2 },
    { id: 'p3', url: '/images/оф107-3.jpg', order: 3 },
    { id: 'p4', url: '/images/оф107-4.jpg', order: 4 },
    { id: 'p5', url: '/images/оф107-5.jpg', order: 5 },
    { id: 'p6', url: '/images/оф107-6.jpg', order: 6 },
    { id: 'p8', url: '/images/оф107-8.jpg', order: 7 },
  ],
}

export const MOCK_BUILDING_ORGS = [
  {
    id: 'org-1',
    name: 'Кафе «Бузовар»',
    category: 'food',
    description: 'Уютное кафе с домашней кухней и бизнес-ланчами',
    floor: 1,
    color: 'amber',
    order: 0,
    active: true,
    website: null,
  },
  {
    id: 'org-2',
    name: 'Пинобар',
    category: 'food',
    description: 'Кофейня и снеки — идеально для быстрого перекуса',
    floor: 1,
    color: 'orange',
    order: 1,
    active: true,
    website: null,
  },
  {
    id: 'org-3',
    name: 'Копицентр',
    category: 'service',
    description: 'Печать, сканирование, ламинирование, брошюровка',
    floor: 2,
    color: 'blue',
    order: 2,
    active: true,
    website: null,
  },
  {
    id: 'org-4',
    name: 'Банкомат Сбербанка',
    category: 'bank',
    description: null,
    floor: 1,
    color: 'green',
    order: 3,
    active: true,
    website: null,
  },
  {
    id: 'org-5',
    name: 'Аптека «Здоровье»',
    category: 'retail',
    description: 'Лекарства, витамины, медицинские товары',
    floor: 1,
    color: 'teal',
    order: 4,
    active: true,
    website: null,
  },
]
