import type { Room } from './types'

// Мок-данные — slugs совпадают с OffersPreview
// TODO Sprint 1: заменить на Prisma запросы
export const MOCK_ROOMS: Room[] = [
  {
    id: '1',
    slug: 'office-400b-1',
    title: 'Офис 400б/1',
    buildingNumber: null,
    roomNumber: '400б/1',
    type: 'Офис',
    area: 36.0,
    floor: 4,
    layoutType: 'Открытая планировка',
    water: false,
    wc: false,
    windows: true,
    entrance: 'Центральный вход',
    rentType: 'Долгосрочная аренда',
    internet: 'Оптоволокно до 1 Гбит/с',
    minRentTerm: 'от 3 месяцев',
    priceMonth: 25000,
    priceM2: 694,
    description:
      '<p>Светлый офис с панорамными окнами на 4 этаже. Хорошее естественное освещение в течение всего рабочего дня, вид на центральную улицу.</p><p>Подходит для небольших команд до 8 человек. Свободная планировка позволяет организовать рабочее пространство под любые задачи.</p>',
    suitableFor: ['IT-компании', 'Дизайн-студии', 'Маркетинг', 'Консалтинг'],
    status: 'FREE',
    hidePrice: false,
    showOnHome: true,
    photos: [
      { id: 'p1', url: 'https://picsum.photos/seed/off-a1/1200/800', order: 0 },
      { id: 'p2', url: 'https://picsum.photos/seed/off-a2/1200/800', order: 1 },
      { id: 'p3', url: 'https://picsum.photos/seed/off-a3/1200/800', order: 2 },
    ],
  },
  {
    id: '2',
    slug: 'office-301-2',
    title: 'Офис 301/2',
    buildingNumber: null,
    roomNumber: '301/2',
    type: 'Офис',
    area: 24.5,
    floor: 3,
    layoutType: 'Кабинетная планировка',
    water: true,
    wc: false,
    windows: true,
    entrance: 'Центральный вход',
    rentType: 'Долгосрочная аренда',
    internet: 'Оптоволокно до 1 Гбит/с',
    minRentTerm: 'от 6 месяцев',
    priceMonth: 18000,
    priceM2: 735,
    description:
      '<p>Уютный кабинетный офис на 3 этаже с водоснабжением. Идеально подходит для небольшой команды или частного кабинета специалиста.</p><p>Готов к заезду — имеется базовая отделка и подведены все коммуникации.</p>',
    suitableFor: ['Юридические услуги', 'Бухгалтерия', 'Психология', 'Медицинские услуги'],
    status: 'FREE',
    hidePrice: false,
    showOnHome: true,
    photos: [{ id: 'p4', url: 'https://picsum.photos/seed/off-b1/1200/800', order: 0 }],
  },
  {
    id: '3',
    slug: 'office-502-a',
    title: 'Офис 502/А',
    buildingNumber: null,
    roomNumber: '502/А',
    type: 'Офис',
    area: 48.0,
    floor: 5,
    layoutType: 'Открытая планировка',
    water: false,
    wc: false,
    windows: true,
    entrance: 'Центральный вход',
    rentType: 'Долгосрочная аренда',
    internet: 'Оптоволокно до 1 Гбит/с',
    minRentTerm: 'от 3 месяцев',
    priceMonth: 34000,
    priceM2: 708,
    description:
      '<p>Просторный офис на 5 этаже с великолепным видом. Открытая планировка позволяет разместить до 15 рабочих мест.</p><p>Высокие потолки, хорошая вентиляция, стеклянные перегородки по запросу.</p>',
    suitableFor: ['IT-компании', 'Рекламные агентства', 'Стартапы', 'Образование'],
    status: 'FREE',
    hidePrice: false,
    showOnHome: true,
    photos: [
      { id: 'p5', url: 'https://picsum.photos/seed/off-c1/1200/800', order: 0 },
      { id: 'p6', url: 'https://picsum.photos/seed/off-c2/1200/800', order: 1 },
    ],
  },
  {
    id: '4',
    slug: 'office-210-1',
    title: 'Офис 210/1',
    buildingNumber: null,
    roomNumber: '210/1',
    type: 'Офис',
    area: 18.0,
    floor: 2,
    layoutType: 'Кабинетная планировка',
    water: true,
    wc: false,
    windows: true,
    entrance: 'Центральный вход',
    rentType: 'Краткосрочная или долгосрочная',
    internet: 'Оптоволокно до 1 Гбит/с',
    minRentTerm: 'от 1 месяца',
    priceMonth: 13500,
    priceM2: 750,
    description:
      '<p>Компактный офис на 2 этаже с водоснабжением. Отличный вариант для небольшого кабинета специалиста или пары сотрудников.</p><p>Гибкие условия аренды — от 1 месяца.</p>',
    suitableFor: ['ИП', 'Частные специалисты', 'Репетиторство', 'Нотариальные услуги'],
    status: 'RESERVED',
    hidePrice: false,
    showOnHome: true,
    photos: [],
  },
  {
    id: '5',
    slug: 'office-601-3',
    title: 'Офис 601/3',
    buildingNumber: null,
    roomNumber: '601/3',
    type: 'Офис',
    area: 72.0,
    floor: 6,
    layoutType: 'Открытая планировка',
    water: true,
    wc: true,
    windows: true,
    entrance: 'Центральный вход',
    rentType: 'Долгосрочная аренда',
    internet: 'Оптоволокно до 1 Гбит/с',
    minRentTerm: 'от 6 месяцев',
    priceMonth: 52000,
    priceM2: 722,
    description:
      '<p>Флагманский офис на 6 этаже — самый просторный в бизнес-центре. Панорамный вид на город, собственный санузел, мини-кухня.</p><p>Подходит для компании с командой 20+ человек или организации офиса класса А.</p>',
    suitableFor: ['Крупные компании', 'IT', 'Финансы', 'Юридические фирмы'],
    status: 'FREE',
    hidePrice: false,
    showOnHome: true,
    photos: [],
  },
  {
    id: '6',
    slug: 'office-105-b',
    title: 'Офис 105/Б',
    buildingNumber: null,
    roomNumber: '105/Б',
    type: 'Офис',
    area: 15.0,
    floor: 1,
    layoutType: 'Кабинетная планировка',
    water: false,
    wc: false,
    windows: false,
    entrance: 'Центральный вход',
    rentType: 'Краткосрочная или долгосрочная',
    internet: 'Оптоволокно до 1 Гбит/с',
    minRentTerm: 'от 1 месяца',
    priceMonth: 11000,
    priceM2: 733,
    description:
      '<p>Бюджетный офис на 1 этаже — минимальная стоимость при хорошем расположении. Подходит для хранения документов, небольшого кабинета или переговорной.</p>',
    suitableFor: ['ИП', 'Хранение документов', 'Частные специалисты'],
    status: 'RENTED',
    hidePrice: false,
    showOnHome: false,
    photos: [],
  },
  {
    id: '7',
    slug: 'sklad-14',
    title: 'Склад №14',
    buildingNumber: null,
    roomNumber: '14',
    type: 'Склад',
    area: 70.0,
    floor: 1,
    layoutType: 'Открытое хранение',
    water: false,
    wc: false,
    windows: false,
    entrance: 'Отдельный вход',
    rentType: 'Долгосрочная аренда',
    internet: null,
    minRentTerm: 'от 3 месяцев',
    priceMonth: 28000,
    priceM2: 400,
    description:
      '<p>Тёплый склад на первом этаже с отдельным входом. Доступ до 20:00. Высота потолков — 3,5\u00a0м, удобная погрузка.</p><p>Арендная плата включает только стоимость помещения. Электричество и отопление оплачиваются отдельно по показаниям индивидуальных счётчиков.</p>',
    suitableFor: [
      'Хранение товаров',
      'Интернет-магазины',
      'Мелкооптовая торговля',
      'Архив документов',
    ],
    status: 'FREE',
    hidePrice: false,
    showOnHome: false,
    photos: [{ id: 'p-s1', url: 'https://picsum.photos/seed/sklad-a1/1200/800', order: 0 }],
  },
  {
    id: '8',
    slug: 'sklad-07',
    title: 'Склад №7',
    buildingNumber: null,
    roomNumber: '7',
    type: 'Склад',
    area: 42.0,
    floor: 1,
    layoutType: 'Открытое хранение',
    water: true,
    wc: false,
    windows: false,
    entrance: 'Отдельный вход',
    rentType: 'Краткосрочная или долгосрочная',
    internet: null,
    minRentTerm: 'от 1 месяца',
    priceMonth: 16800,
    priceM2: 400,
    description:
      '<p>Компактный тёплый склад с водоснабжением. Гибкие условия — аренда от 1\u00a0месяца. Отдельный вход, доступ в рабочее время.</p><p>Подходит для хранения товаров, архива, оборудования. Электричество по счётчику.</p>',
    suitableFor: ['Хранение товаров', 'Архив документов', 'Оборудование', 'ИП'],
    status: 'RESERVED',
    hidePrice: false,
    showOnHome: false,
    photos: [],
  },
]
