import type { Lead } from './types'

export const MOCK_LEADS: Lead[] = [
  {
    id: '1',
    createdAt: '2026-03-14T10:23:00',
    name: 'Иван Петров',
    phone: '+7 (913) 123-45-67',
    email: 'ivan.petrov@gmail.com',
    message: 'Интересует аренда офиса на длительный срок. Готовы рассмотреть варианты от 30 м².',
    roomId: 'office-201',
    roomTitle: 'Офис 400б/1',
    serviceName: null,
    status: 'NEW',
  },
  {
    id: '2',
    createdAt: '2026-03-14T09:05:00',
    name: 'ООО «Сибирь-Трейд»',
    phone: '+7 (383) 222-33-44',
    email: 'info@sibirtrade.ru',
    message:
      'Нужен склад для хранения товаров. Площадь от 50 м². Возможна ли аренда с понедельного оплатой?',
    roomId: 'sklad-a1',
    roomTitle: 'Склад А1',
    serviceName: null,
    status: 'NEW',
  },
  {
    id: '3',
    createdAt: '2026-03-13T16:44:00',
    name: 'Мария Соколова',
    phone: '+7 (923) 456-78-90',
    email: null,
    message: 'Хочу арендовать небольшой офис для начинающего ИП.',
    roomId: null,
    roomTitle: null,
    serviceName: null,
    status: 'NEW',
  },
  {
    id: '4',
    createdAt: '2026-03-13T11:20:00',
    name: 'Алексей Громов',
    phone: '+7 (953) 789-01-23',
    email: 'a.gromov@mail.ru',
    message: 'Уточните, пожалуйста, условия парковки для арендаторов.',
    roomId: null,
    roomTitle: null,
    serviceName: 'Парковка',
    status: 'IN_PROGRESS',
  },
  {
    id: '5',
    createdAt: '2026-03-12T14:55:00',
    name: 'ИП Кузнецова Е.В.',
    phone: '+7 (913) 321-65-87',
    email: 'kuznetsova@yandex.ru',
    message: 'Планируем открытие в апреле. Нужен офис с отдельным входом.',
    roomId: 'office-302',
    roomTitle: 'Офис 302',
    serviceName: null,
    status: 'IN_PROGRESS',
  },
  {
    id: '6',
    createdAt: '2026-03-12T10:10:00',
    name: 'Дмитрий Лебедев',
    phone: '+7 (383) 444-55-66',
    email: 'lebedev@biz.ru',
    message: 'Интересует аренда переговорной комнаты на несколько часов.',
    roomId: null,
    roomTitle: null,
    serviceName: 'Переговорная',
    status: 'PROCESSED',
  },
  {
    id: '7',
    createdAt: '2026-03-11T17:30:00',
    name: 'Светлана Новикова',
    phone: '+7 (923) 111-22-33',
    email: 'novikova@company.ru',
    message: 'Рассматриваем переезд офиса. Нужно помещение 60-80 м² на 1-2 этаже.',
    roomId: 'office-105',
    roomTitle: 'Офис 105',
    serviceName: null,
    status: 'PROCESSED',
  },
  {
    id: '8',
    createdAt: '2026-03-10T09:45:00',
    name: 'АО «НовосибТех»',
    phone: '+7 (383) 777-88-99',
    email: 'office@nsk-tech.ru',
    message: 'Нас интересует аренда нескольких помещений для IT-компании. Общая площадь 200+ м².',
    roomId: null,
    roomTitle: null,
    serviceName: null,
    status: 'PROCESSED',
  },
]
